#!/bin/sh

PORT=/dev/ttyUSB0
UPLOAD_RATE=57600
AVRDUDE_PROGRAMMER=stk500v1
MCU=atmega644p

# grab firmware filepath from param $1 if supplied
FIRMWARE_FILE=firmware/honeyplot.hex
if [ $1 ]
    then
        FIRMWARE_FILE=$1
fi

AVRDUDE_PATH=/usr/bin
AVRDUDE_CONF_PATH=/etc

AVRDUDE=$AVRDUDE_PATH/avrdude

AVRDUDE_PORT=$PORT
AVRDUDE_WRITE_FLASH="-U flash:w:$FIRMWARE_FILE"

AVRDUDE_FLAGS="-V -F -C $AVRDUDE_CONF_PATH/avrdude.conf \
-p $MCU -P $AVRDUDE_PORT -c $AVRDUDE_PROGRAMMER \
-b $UPLOAD_RATE -D"

$AVRDUDE $AVRDUDE_FLAGS $AVRDUDE_WRITE_FLASH $FIRMWARE_FILE