#!/bin/sh

PORT=/dev/ttyUSB0
UPLOAD_RATE=57600
AVRDUDE_PROGRAMMER=stk500v1
MCU=atmega644p

OUTPUT_DIR=firmware

AVRDUDE_PATH=/usr/bin
AVRDUDE_CONF_PATH=/etc

AVRDUDE=$AVRDUDE_PATH/avrdude

FILENAME=honeyplot

AVRDUDE_PORT=$PORT
AVRDUDE_WRITE_FLASH="-U flash:w:$OUTPUT_DIR/$FILENAME.hex"

AVRDUDE_FLAGS="-V -F -C $AVRDUDE_CONF_PATH/avrdude.conf \
-p $MCU -P $AVRDUDE_PORT -c $AVRDUDE_PROGRAMMER \
-b $UPLOAD_RATE -D"

$AVRDUDE $AVRDUDE_FLAGS $AVRDUDE_WRITE_FLASH $OUTPUT_DIR/$FILENAME.hex